const ROSTER_NAMES = [
  'Abhishek Kumar Singh',
  'Abhishek Lingwal',
  'Akashdeep Balu',
  'Anil Mallapur',
  'Anjan Kumar',
  'Arpan Dey',
  'Arjun Deb',
  'Arjun Shukla',
  'Chaitanya Teja Golla',
  'Eshwar Chaitanya Sarampati',
  'Gaurav Kumar',
  'Gaurav Mehta',
  'Hari Vangipuram',
  'Jay Shah',
  'Kaushal Karkera',
  'Kunal Kokate',
  'Lokesh Bala',
  'Meet Dhabalia',
  'Mithal Kothari',
  'Piyush Jha',
  'Prashant Kumar',
  'Praveen Karkhile',
  'Rajeev Tirumala',
  'Rijwan Rana',
  'Rohit Sharma',
  'Samir Savla',
  'Shriganesh Shintre',
  'Soumya Smruti Mishra',
];
