const ROSTER_NAMES = [
  'Aakash Agnihotri',
  'Abhishek Kumar Singh',
  'Abhishek Lingwal',
  'Ajay Joy',
  'Akashdeep Balu',
  'Akshay Garg',
  'Aman Kohli',
  'Anil Mallapur',
  'Anjan Kumar',
  'Ankit Agarwal',
  'Arpan Dey',
  'Arjun Deb',
  'Arjun Shukla',
  'Ashish Chanchalani',
  'Chaitanya Teja Golla',
  'Eshwar Chaitanya Sarampati',
  'Gaurav Kumar',
  'Gaurav Mehta',
  'Hari Vangipuram',
  'Harsha Vardhan Reddy Vndavally',
  'Jay Shah',
  'Jimit Majmudar',
  'Kaushal Karkera',
  'Kunal Kokate',
  'Lokesh Bala',
  'Meet Dhabalia',
  'Mithal Kothari',
  'Mohan Challa',
  'Piyush Jha',
  'Prashant Kumar',
  'Praveen Karkhile',
  'Rajeev Tirumala',
  'Rijwan Rana',
  'Rohit Sharma',
  'Samir Savla',
  'Santosh Ghosh',
  'Shashank Dube',
  'Shivang Sharma',
  'Shriganesh Shintre',
  'Smit Paul',
  'Soumya Smruti Mishra',
  'Srinath Shah',
  'Subham Satapathy',
  'Sylvestor George',
  'Tarang Thapa',
  'Tarun Joshi',
  'Venkata Krishna Ravi',
  'Vignesh Ganguly',
  'Vinay Bharbhari',
  'Vivek Garg',
  'Yash Mehta',
];
